# Generated by Django 4.0.2 on 2022-03-27 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Commentairechapitre',
        ),
    ]
