# Generated by Django 4.0.2 on 2022-04-03 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0003_manga_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vuechapitre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
