# Generated by Django 4.0.2 on 2022-04-03 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0004_vuechapitre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vuechapitre',
        ),
    ]
