# Generated by Django 4.0.2 on 2022-03-12 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0004_manga'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='manga',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
