# Generated by Django 4.0.2 on 2022-03-12 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0005_manga_comment_manga_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='slug',
            field=models.SlugField(blank=True, default=''),
        ),
    ]
