# Generated by Django 4.0.2 on 2022-03-19 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0006_manga_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manga',
            name='comment',
        ),
        migrations.CreateModel(
            name='Commentairechapitre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo', models.CharField(default='', max_length=30)),
                ('comment', models.TextField(default='')),
                ('date', models.CharField(default='', max_length=30)),
                ('manga', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp1.manga')),
            ],
        ),
    ]
