# Generated by Django 4.0.2 on 2022-03-27 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0007_remove_manga_comment_commentairechapitre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Commentairechapitre',
        ),
        migrations.DeleteModel(
            name='Manga',
        ),
    ]
