# Generated by Django 4.0.2 on 2022-03-27 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapitre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('description', models.TextField(default='')),
                ('slug', models.SlugField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Commentairechapitre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo', models.CharField(default='', max_length=30)),
                ('comment', models.TextField(default='')),
                ('date', models.CharField(default='', max_length=30)),
                ('chapitre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chapitre.chapitre')),
            ],
        ),
    ]
