# Generated by Django 4.0.2 on 2022-03-27 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0002_delete_commentairechapitre'),
        ('chapitre', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapitre',
            name='manga',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manga.manga'),
        ),
    ]
