# Generated by Django 4.0.2 on 2022-06-04 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chapitre', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vuechapitre',
            old_name='pseudo',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='commentairechapitre',
            name='pseudo',
        ),
        migrations.RemoveField(
            model_name='likechapitre',
            name='pseudo',
        ),
        migrations.AddField(
            model_name='commentairechapitre',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='likechapitre',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
