# Generated by Django 4.1 on 2022-08-22 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapitre', '0002_rename_pseudo_vuechapitre_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangementComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
