# Generated by Django 4.0.2 on 2022-04-02 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chapitre', '0002_chapitre_manga'),
    ]

    operations = [
        migrations.CreateModel(
            name='Likechapitre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo', models.CharField(default='', max_length=30)),
                ('chapitre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chapitre.chapitre')),
            ],
        ),
    ]
