# Generated by Django 4.1 on 2022-08-22 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chapitre', '0003_changementcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='changementcomment',
            name='chapitreid',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='chapitre.chapitre'),
        ),
    ]
