# Generated by Django 4.0.2 on 2022-08-26 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chapitre', '0004_changementcomment_chapitreid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='changementcomment',
            old_name='chapitreid',
            new_name='chapitre',
        ),
    ]
