# Generated by Django 4.0.2 on 2022-04-03 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapitre', '0004_imageschapitre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageschapitre',
            name='name',
        ),
        migrations.AddField(
            model_name='imageschapitre',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='images'),
        ),
    ]
