# Generated by Django 4.0.2 on 2022-04-03 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chapitre', '0005_remove_imageschapitre_name_imageschapitre_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vuechapitre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo', models.CharField(default='', max_length=30)),
                ('chapitre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chapitre.chapitre')),
            ],
        ),
    ]
