# Generated by Django 4.0.2 on 2022-04-10 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapitre', '0006_vuechapitre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentairechapitre',
            name='pseudo',
            field=models.CharField(default='bidon', max_length=30),
        ),
    ]
