# Generated by Django 4.0.2 on 2023-05-07 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapitre', '0006_alter_imageschapitre_chapitre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imageschapitre',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='imageschapitre',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
