# Generated by Django 4.0.2 on 2023-05-07 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapitre', '0007_alter_imageschapitre_options_imageschapitre_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageschapitre',
            name='order',
            field=models.IntegerField(blank=True, default=20000, null=True),
        ),
    ]
