# Generated by Django 4.0.2 on 2022-04-10 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapitre', '0007_alter_commentairechapitre_pseudo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentairechapitre',
            name='pseudo',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
