# Generated by Django 4.0.2 on 2023-05-07 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapitre', '0009_alter_imageschapitre_chapitre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageschapitre',
            name='order',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
